//#file：./tab/action.xlsx, sheet：action，output：action.cs

using System.Collections.Generic;

public class Table_action
{
	public struct Data
	{
		public string id;
		public bool ifSpecial;
		public string name;
		public int cost;
		public List<string> element;
		public List<string> actionTypes;
		public List<string> functions;
		public string description;
		public string faceimage;
		public string backImage;
		public string faceCenter;
		public int type ;

		public Data(string _id = "", bool _ifSpecial = false, string _name = "", int _cost = 0, List<string> _element = null, List<string> _actionTypes = null, List<string> _functions = null, string _description = "", string _faceimage = "", string _backImage = "", string _faceCenter = "", int _type  = 0)
		{
			id = _id;
			ifSpecial = _ifSpecial;
			name = _name;
			cost = _cost;
			element = _element;
			actionTypes = _actionTypes;
			functions = _functions;
			description = _description;
			faceimage = _faceimage;
			backImage = _backImage;
			faceCenter = _faceCenter;
			type  = _type ;
		}
	}
	public static Dictionary<string, Data> data = new Dictionary<string, Data> {
		{"tactic_0001", new Data(_id: "tactic_0001", _ifSpecial: false, _name: "Flank Assault", _cost: 1, _element: new List<string>(){ "METAL" }, _actionTypes: new List<string>(){ "ATTACK" }, _functions: new List<string>(){ @"{""from"":""ALL_CAVALRY"", ""target"":""FLANKS_ENEMY"",""effect"":""PRIOTIZED_ATTACK"", ""basicValueExpression"":""3""}" }, _description: "Your cavalry deals 2 charge damage to the enemy\'s flanks.", _faceimage: "tactic_0001")},
		{"tactic_0002", new Data(_id: "tactic_0002", _ifSpecial: false, _name: "Feigned Retreat", _cost: 2, _element: new List<string>(){ "WOOD" }, _actionTypes: new List<string>(){ "DEFENSE", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""ALL_CAVALRY"",""target"":""ALL_FRIEND"",""effect"":""ELASTIC_DEFENSE"",""basicValueExpression"":3}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""COUNTERATTACK_MODIFIER"",""basicValueExpression"":""2""}" }, _description: "Provide 2 points of Flexible Defense to allies; the counterattack is 40% more effective.", _faceimage: "tactic_0002", _faceCenter: " ")},
		{"tactic_0003", new Data(_id: "tactic_0003", _ifSpecial: false, _name: "Maneuver Encirclement", _cost: 3, _element: new List<string>(){ "WATER" }, _actionTypes: new List<string>(){ "SPECIAL", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_AFTER_TURN"",""basicValueExpression"":""1""}", @"{""from"":""ALL_CAVALRY"", ""target"":""BACK_ENEMY"",""effect"":""PRIOTIZED_ATTACK"",""basicValueExpression"":""WATER_CARD_PLAYED*3""}" }, _description: "Your cavalry Leaves the battlefield this turn, dealing 3 Charge Damage per water card used this turn to the enemy\'s rear next turn.", _faceimage: "tactic_0003")},
		{"tactic_0004", new Data(_id: "tactic_0004", _ifSpecial: false, _name: "Repeated Charge", _cost: 1, _element: new List<string>(){ "FIRE" }, _actionTypes: new List<string>(){ "ATTACK", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""ALL_CAVALRY"", ""target"":""FRONT_ENEMY"",""effect"":""PRIOTIZED_ATTACK"", ""basicValueExpression"":""1.5""}", @"{""from"":""ALL_CAVALRY"",""target"":""FRONT_ENEMY"",""effect"":""PRIOTIZED_ATTACK"", ""basicValueExpression"":""1.5""}" }, _description: "Your cavalry deals twice of 1 charge damage to the enemy\'s front line.", _faceimage: "tactic_0004")},
		{"tactic_0005", new Data(_id: "tactic_0005", _ifSpecial: false, _name: "Flexible Defense", _cost: 2, _element: new List<string>(){ "EARTH" }, _actionTypes: new List<string>(){ "DEFENSE", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""ALL_CAVALRY"",""target"":""ALL_FRIEND"",""effect"":""ELASTIC_DEFENSE"",""basicValueExpression"":""3""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""MORAL"",""basicValueExpression"":""1""}" }, _description: "Provide 2 Flexible Defense and 2 Morale to allies.", _faceimage: "tactic_0005")},
		{"tactic_0006", new Data(_id: "tactic_0006", _ifSpecial: true, _name: "Iron Force", _cost: 2, _element: new List<string>(){ "METAL", "WATER" }, _actionTypes: new List<string>(){ "DEFENSE", "ATTACK", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""ARMOUR_DEFENSE"",""basicValueExpression"":""2""}", @"{""from"":""ALL_FRIEND"", ""target"":""FRONT_ENEMY"",""effect"":""PRIOTIZED_ATTACK"",""basicValueExpression"":""2""}", @"{""from"":""ALL_FRIEND"", ""target"":""FRONT_ENEMY"",""effect"":""MELEE_ATTACK"",""basicValueExpression"":""2""}" }, _description: "Gain 1/1.2/1.5 Armor Defense, deal 2/2.5/3 Impact Damage and 2/2.5/3 Melee Damage to the enemy\'s front line.", _faceimage: "tactic_0006")},
		{"tactic_0007", new Data(_id: "tactic_0007", _ifSpecial: true, _name: "Wave Propagation", _cost: 2, _element: new List<string>(){ "WOOD", "WATER" }, _actionTypes: new List<string>(){ "ATTACK", "ATTACK", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""FLANKS_ENEMY"",""effect"":""ARMOUR_PIERCING_ATTACK"",""basicValueExpression"":""2""}", @"{""from"":""ALL_FRIEND"", ""target"":""FLANKS_ENEMY"",""effect"":""PRIOTIZED_ATTACK"",""basicValueExpression"":""2""}", @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""COUNTERATTACK_MODIFIER"",""basicValueExpression"":""-1""}" }, _description: "Deal 2/2.5/3 Projectile Damage and 2/2.5/3 Impact Damage to the enemy\'s flank; enemy\'s counterattack effectiveness is reduced by 20%/25%/30%.", _faceimage: "tactic_0007")},
		{"tactic_0008", new Data(_id: "tactic_0008", _ifSpecial: true, _name: "Stormy Waves", _cost: -1, _element: new List<string>(){ "WATER", "WATER" }, _actionTypes: new List<string>(){ "ATTACK" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""PRIOTIZED_ATTACK"",""basicValueExpression"":""REMAINING_ACTION_POINT*2""}" }, _description: "Consume all remaining action points to deal 2x/2.5x/3x Charge Damage to the entire enemy army.", _faceimage: "tactic_0008")},
		{"tactic_0009", new Data(_id: "tactic_0009", _ifSpecial: true, _name: "Fireworks", _cost: 3, _element: new List<string>(){ "FIRE", "WATER" }, _actionTypes: new List<string>(){ "ATTACK", "SPECIAL", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""FLANKS_ENEMY"",""effect"":""PROJECTILE_ATTACK"",""basicValueExpression"":""2""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""MORAL_DAMAGE_MODIFIER"",""basicValueExpression"":""3""}", @"{""from"":""ALL_FRIEND"", ""target"":""FLANKS_ENEMY"",""effect"":""PRIOTIZED_ATTACK"",""basicValueExpression"":""2""}" }, _description: "Deal 2/2.5/3 Armor Penetration Damage and 2/2.5/3 Impact Damage to the enemy, striking the enemy\'s discipline by 2/2.5/3 times.", _faceimage: "tactic_0009")},
		{"tactic_0010", new Data(_id: "tactic_0010", _ifSpecial: true, _name: "Effortless Success", _cost: 1, _element: new List<string>(){ "EARTH", "WATER" }, _actionTypes: new List<string>(){ "SPECIAL", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""FLANKS_FRIEND"",""effect"":""IGNORE_DEFENSE"",""basicValueExpression"":""1""}", @"{""from"":""FLANKS_FRIEND"", ""target"":""FLANKS_ENEMY"",""effect"":""MELEE_ATTACK"",""basicValueExpression"":""2""}" }, _description: "Ignore negative terrain effects, deal 2/2.5/3 Impact Damage to the enemy\'s flank.", _faceimage: "tactic_0010")},
		{"tactic_0011", new Data(_id: "tactic_0011", _ifSpecial: false, _name: "Hold the Line", _cost: 3, _element: new List<string>(){ "METAL" }, _actionTypes: new List<string>(){ "DEFENSE", "DEFENSE" }, _functions: new List<string>(){ @"{""from"":""ALL_HEAVY"", ""target"":""CENTER_FRIEND"",""effect"":""ARMOUR_DEFENSE"",""basicValueExpression"":""METAL_CARD_PLAYED*3""}", @"{""from"":""ALL_HEAVY"", ""target"":""CENTER_FRIEND"",""effect"":""FORMATION_DEFENSE"",""basicValueExpression"":""METAL_CARD_PLAYED*3""}" }, _description: "Provide 3Armor Defense,3Line Defense per metal card played", _faceimage: "tactic_0011")},
		{"tactic_0012", new Data(_id: "tactic_0012", _ifSpecial: false, _name: "Counterattack", _cost: 2, _element: new List<string>(){ "WOOD" }, _actionTypes: new List<string>(){ "DEFENSE", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""ALL_HEAVY"", ""target"":""ALL_FRIEND"",""effect"":""ARMOUR_DEFENSE"",""basicValueExpression"":""3""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""COUNTERATTACK_MODIFIER"",""basicValueExpression"":""1""}" }, _description: "Provide 2/2.5/3 Armor Defense to allies; defense counterattack effect increased by 20%/25%/30%.", _faceimage: "tactic_0012")},
		{"tactic_0013", new Data(_id: "tactic_0013", _ifSpecial: false, _name: "Rapid Maneuver", _cost: 2, _element: new List<string>(){ "WATER" }, _actionTypes: new List<string>(){ "SPECIAL", "ATTACK", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""IGNORE_DEFENSE"",""basicValueExpression"":""1""}", @"{""from"":""ALL_HEAVY"", ""target"":""FLANKS_ENEMY"",""effect"":""PRIOTIZED_ATTACK"",""basicValueExpression"":""1.5""}", @"{""from"":""ALL_HEAVY"", ""target"":""FLANKS_ENEMY"",""effect"":""MELEE_ATTACK"",""basicValueExpression"":""1.5""}" }, _description: "Ignoring Defense effects, deal 1.5 Impact Damage and 1.5 Melee Damage to the enemy\'s flank.", _faceimage: "tactic_0013")},
		{"tactic_0014", new Data(_id: "tactic_0014", _ifSpecial: false, _name: "Assault Charge", _cost: 1, _element: new List<string>(){ "FIRE" }, _actionTypes: new List<string>(){ "ATTACK", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""ALL_HEAVY"", ""target"":""FRONT_ENEMY"",""effect"":""PRIOTIZED_ATTACK"",""basicValueExpression"":""1.5""}", @"{""from"":""ALL_HEAVY"", ""target"":""FRONT_ENEMY"",""effect"":""MELEE_ATTACK"",""basicValueExpression"":""1.5""}" }, _description: "Deal 1/1.2/1.5 Impact Damage and 1/1.2/1.5 Melee Damage to the enemy\'s front line.", _faceimage: "tactic_0014")},
		{"tactic_0015", new Data(_id: "tactic_0015", _ifSpecial: false, _name: "Position Defense", _cost: 1, _element: new List<string>(){ "EARTH" }, _actionTypes: new List<string>(){ "DEFENSE" }, _functions: new List<string>(){ @"{""from"":""ALL_HEAVY"", ""target"":""ALL_FRIEND"",""effect"":""ARMOUR_DEFENSE"",""basicValueExpression"":""3""}" }, _description: "Provide 2/2.5/3 Armor Defense to allies.", _faceimage: "tactic_0015")},
		{"tactic_0016", new Data(_id: "tactic_0016", _ifSpecial: true, _name: "Iron Wall", _cost: -1, _element: new List<string>(){ "METAL", "METAL" }, _actionTypes: new List<string>(){ "DEFENSE", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""ARMOUR_DEFENSE"",""basicValueExpression"":""2""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""INHERIT_ALL_DEFENSE"",""basicValueExpression"":""1""}" }, _description: "Consume all remaining action points to provide 2x/2.5x/3x Armor Defense and carry over the Armor Defense to the next turn.", _faceimage: "tactic_0016")},
		{"tactic_0017", new Data(_id: "tactic_0017", _ifSpecial: true, _name: "Metal-Wood Alliance", _cost: 3, _element: new List<string>(){ "WOOD", "METAL" }, _actionTypes: new List<string>(){ "DEFENSE", "DEFENSE", "DEFENSE" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""ELASTIC_DEFENSE"",""basicValueExpression"":""2""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""FORMATION_DEFENSE"",""basicValueExpression"":""2""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""ARMOUR_DEFENSE"",""basicValueExpression"":""2""}" }, _description: "Provide 2/2.5/3 Armor Defense, Flexible Defense, and Pike Defense to the entire army.", _faceimage: "tactic_0017")},
		{"tactic_0018", new Data(_id: "tactic_0018", _ifSpecial: true, _name: "Mercurial Flood", _cost: 2, _element: new List<string>(){ "WATER", "METAL" }, _actionTypes: new List<string>(){ "SPECIAL", "ATTACK", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""IGNORE_DEFENSE"",""basicValueExpression"":""1""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""PROJECTILE_ATTACK"",""basicValueExpression"":""1.5""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""PRIOTIZED_ATTACK"",""basicValueExpression"":""1.5""}" }, _description: "Deal 2/2.5/3 Impact Damage and 2/2.5/3 Melee Damage to the entire enemy army, ignoring the enemy\'s formation defense effects.", _faceimage: "tactic_0018")},
		{"tactic_0019", new Data(_id: "tactic_0019", _ifSpecial: true, _name: "Stonesplit", _cost: 2, _element: new List<string>(){ "FIRE", "METAL" }, _actionTypes: new List<string>(){ "SPECIAL", "ATTACK", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DEFENSE_DAMAGE_MODIFIER"",""basicValueExpression"":""0.5""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""ARMOUR_PIERCING_ATTACK"",""basicValueExpression"":""2""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""PRIOTIZED_ATTACK"",""basicValueExpression"":""1.5""}" }, _description: "Deal 2/2.5/3 Armor Penetration Damage, 1/1.2/1.5 Impact Damage, and 1/1.2/1.5 Melee Damage to the enemy\'s front line, with 1.5x damage to Line Defense.", _faceimage: "tactic_0019")},
		{"tactic_0020", new Data(_id: "tactic_0020", _ifSpecial: true, _name: "Impenetrable", _cost: 1, _element: new List<string>(){ "EARTH", "METAL" }, _actionTypes: new List<string>(){ "DEFENSE", "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""TERRAIN_DEFENSE"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""MORAL_DAMAGE_MODIFIER"",""basicValueExpression"":""-0.4""}", @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""DISCIPLINE_DAMAGE_MODIFIER"",""basicValueExpression"":""-0.4""}" }, _description: "Provide 1/1.2/2.5 Terrain Defense and Armor Defense to the entire army, and reduce the enemy\'s next round attacks on morale and discipline by 20%/25%/30%.", _faceimage: "tactic_0020")},
		{"tactic_0021", new Data(_id: "tactic_0021", _ifSpecial: false, _name: "Precision Strike", _cost: 2, _element: new List<string>(){ "METAL" }, _actionTypes: new List<string>(){ "SPECIAL", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DEFENSE_DAMAGE_MODIFIER"",""basicValueExpression"":""0.5""}", @"{""from"":""ALL_FRIEND"", ""target"":""FRONT_ENEMY"",""effect"":""ARMOUR_PIERCING_ATTACK"",""basicValueExpression"":""6""}" }, _description: "Deal 6/7.5/9 Armor Penetration Damage to the enemy\'s front line, dealing an additional 50% damage to Armor Defense.", _faceimage: "tactic_0021")},
		{"tactic_0022", new Data(_id: "tactic_0022", _ifSpecial: false, _name: "Guerrilla Tactics", _cost: 1, _element: new List<string>(){ "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""COUNTERATTACK_MODIFIER"",""basicValueExpression"":""-99""}", @"{""from"":""ALL_FRIEND"", ""target"":""FLANKS_ENEMY"",""effect"":""ARMOUR_PIERCING_ATTACK"",""basicValueExpression"":""3""}" }, _description: "Deal 2/2.5/3 Armor Penetration Damage to the enemy\'s flank, gain 2/2.5/3 Flexible Defense, ignoring counterattack effects.", _faceimage: "tactic_0022")},
		{"tactic_0023", new Data(_id: "tactic_0023", _ifSpecial: false, _name: "Turning Fire", _cost: 2, _element: new List<string>(){ "WATER" }, _actionTypes: new List<string>(){ "ATTACK", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""FLANKS_ENEMY"",""effect"":""ARMOUR_PIERCING_ATTACK"",""basicValueExpression"":""3""}", @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""ACTION_POINT_NEXT_TURN"",""basicValueExpression"":""1""}" }, _description: "Deal 4/5/6 Armor Penetration Damage to the enemy\'s flank, gain an extra action point next turn.", _faceimage: "tactic_0023")},
		{"tactic_0024", new Data(_id: "tactic_0024", _ifSpecial: false, _name: "Line Fire", _cost: 1, _element: new List<string>(){ "FIRE" }, _actionTypes: new List<string>(){ "ATTACK" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""FRONT_ENEMY"",""effect"":""ARMOUR_PIERCING_ATTACK"",""basicValueExpression"":""FIRE_CARD_PLAYED""}" }, _description: "Deal 1Armor Penetration Damage per fire card played to the enemy\'s front line.", _faceimage: "tactic_0024")},
		{"tactic_0025", new Data(_id: "tactic_0025", _ifSpecial: false, _name: "Suppressive Fire", _cost: 3, _element: new List<string>(){ "EARTH" }, _actionTypes: new List<string>(){ "ATTACK", "DEFENSE", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""FRONT_ENEMY"",""effect"":""SIEGE_ATTACK"",""basicValueExpression"":""3""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""ELASTIC_DEFENSE"",""basicValueExpression"":""3""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""COUNTERATTACK_MODIFIER"",""basicValueExpression"":""1""}" }, _description: "Deal 1/1.2/1.5 Armor Penetration Damage to the enemy\'s front line, provide 1/1.2/1.5 Suppression Defense to allies, and increase flexible counterattack effects by 20%/25%/30%.", _faceimage: "tactic_0025")},
		{"tactic_0026", new Data(_id: "tactic_0026", _ifSpecial: true, _name: "Strike While Hot", _cost: 2, _element: new List<string>(){ "METAL", "FIRE" }, _actionTypes: new List<string>(){ "ATTACK", "ATTACK", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""FRONT_ENEMY"",""effect"":""ARMOUR_PIERCING_ATTACK"",""basicValueExpression"":""2""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""MELEE_ATTACK"",""basicValueExpression"":""2""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_POINT_NEXT_TURN"",""basicValueExpression"":""1""}" }, _description: "Can only be used after a Fire Tactics move; deal 2/2.5/3 Armor Penetration Damage and 2/2.5/3 Melee Damage to the enemy, gain an action point.", _faceimage: "tactic_0026")},
		{"tactic_0027", new Data(_id: "tactic_0027", _ifSpecial: true, _name: "Slash and Burn", _cost: 2, _element: new List<string>(){ "WOOD", "FIRE" }, _actionTypes: new List<string>(){ "ATTACK", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""FRONT_ENEMY"",""effect"":""ARMOUR_PIERCING_ATTACK"",""basicValueExpression"":""4""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DRAW_FIRE_CARD_NEXT_TURN"",""basicValueExpression"":""2""}" }, _description: "Deal 2/2.5/3 Armor Penetration Damage, 1/1.2/1.5 Melee Damage, and Projectile Damage to the enemy, and draw two additional Fire element cards next turn.", _faceimage: "tactic_0027")},
		{"tactic_0028", new Data(_id: "tactic_0028", _ifSpecial: true, _name: "Fire and Water", _cost: 1, _element: new List<string>(){ "WATER", "FIRE" }, _actionTypes: new List<string>(){ "ATTACK", "ATTACK", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""FRONT_ENEMY"",""effect"":""ARMOUR_PIERCING_ATTACK"",""basicValueExpression"":""1""}", @"{""from"":""ALL_FRIEND"", ""target"":""FRONT_ENEMY"",""effect"":""PROJECTILE_ATTACK"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DRAW_WATER_CARD_NEXT_TURN"",""basicValueExpression"":""1""}" }, _description: "Deal 1/1.2/1.5 Armor Penetration Damage and 1/1.2/1.5 Charge Damage to the enemy, draw a Water element card.", _faceimage: "tactic_0028")},
		{"tactic_0029", new Data(_id: "tactic_0029", _ifSpecial: true, _name: "Wildfire", _cost: -1, _element: new List<string>(){ "FIRE", "FIRE" }, _actionTypes: new List<string>(){ "ATTACK", "SPECIAL", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""PROJECTILE_ATTACK"",""basicValueExpression"":""ALL_CARD_NUMBER*2""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""BURN_CARD"",""basicValueExpression"":""20""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""ARMOUR_PIERCING_ATTACK"",""basicValueExpression"":""REMAINING_ACTION_POINT*2""}" }, _description: "Consume all Fire element tactic cards, each card dealing 1x/1.2x/1.5x Armor Penetration Damage to the enemy (including this card).", _faceimage: "tactic_0029")},
		{"tactic_0030", new Data(_id: "tactic_0030", _ifSpecial: true, _name: "Scorching Earth", _cost: 3, _element: new List<string>(){ "EARTH", "FIRE" }, _actionTypes: new List<string>(){ "SPECIAL", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DEFENSE_DAMAGE_MODIFIER"",""basicValueExpression"":""1""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""ARMOUR_PIERCING_ATTACK"",""basicValueExpression"":""6""}" }, _description: "Deal 6/7/9 Armor Penetration Damage to the enemy, ignoring and removing the enemy\'s defensive fortifications.", _faceimage: "tactic_0030")},
		{"tactic_0031", new Data(_id: "tactic_0031", _ifSpecial: false, _name: "Fast Interception", _cost: 1, _element: new List<string>(){ "METAL" }, _actionTypes: new List<string>(){ "ATTACK" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""FRONT_ENEMY"",""effect"":""PRIOTIZED_ATTACK"",""basicValueExpression"":""1.5""}" }, _description: "Deal 2/2.5/3 Charge Damage to the front line.", _faceimage: "tactic_0031")},
		{"tactic_0032", new Data(_id: "tactic_0032", _ifSpecial: false, _name: "Long-Range Support", _cost: 2, _element: new List<string>(){ "WOOD" }, _actionTypes: new List<string>(){ "DEFENSE", "DEFENSE" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""FORMATION_DEFENSE"",""basicValueExpression"":""WOOD_CARD_PLAYED*1""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""ELASTIC_DEFENSE"",""WOOD_CARD_PLAYED"":""1""}" }, _description: "Provide 1 Formation Defense and 1 Flexible Defense per wood card played", _faceimage: "tactic_0032")},
		{"tactic_0033", new Data(_id: "tactic_0033", _ifSpecial: false, _name: "Agile Movement", _cost: 1, _element: new List<string>(){ "WATER" }, _actionTypes: new List<string>(){ "SPECIAL", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""FLANKS_FRIEND"",""effect"":""DEFENSE_DAMAGE_MODIFIER"",""basicValueExpression"":""1""}", @"{""from"":""FLANKS_FRIEND"", ""target"":""FLANKS_ENEMY"",""effect"":""PROJECTILE_ATTACK"",""basicValueExpression"":""1.5""}" }, _description: "Deal 1/1.2/1.5 Melee Damage to the flank, causing an additional 100% damage to Flexible Defense.", _faceimage: "tactic_0033")},
		{"tactic_0034", new Data(_id: "tactic_0034", _ifSpecial: false, _name: "Decisive Charge", _cost: 3, _element: new List<string>(){ "FIRE" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""FLANKS_FRIEND"",""effect"":""MORAL_MULTIPLIER"",""basicValueExpression"":""2""}", @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""COUNTERATTACK_MODIFIER"",""basicValueExpression"":""1""}", @"{""from"":""ALL_FRIEND"", ""target"":""FRONT_ENEMY"",""effect"":""MELEE_ATTACK"",""basicValueExpression"":""4.5""}" }, _description: "For each Wood element card in hand, deal 1/1.2/1.5 Projectile, Charge, and Melee Damage; Morale bonuses are doubled, and friendly units have previously taken double counterattack damage.", _faceimage: "tactic_0034")},
		{"tactic_0035", new Data(_id: "tactic_0035", _ifSpecial: false, _name: "Spear Defense", _cost: 2, _element: new List<string>(){ "EARTH" }, _actionTypes: new List<string>(){ "DEFENSE", "DEFENSE" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""FORMATION_DEFENSE"",""basicValueExpression"":""3""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""ELASTIC_DEFENSE"",""basicValueExpression"":""WOOD_CARD_NUMBER*1""}" }, _description: "Provide 4/5/6 Formation Defense; for each Wood element card in hand, provide an additional 1/1.2/1.5 Formation Defense.", _faceimage: "tactic_0035")},
		{"tactic_0036", new Data(_id: "tactic_0036", _ifSpecial: true, _name: "Strength and Flexibility", _cost: 1, _element: new List<string>(){ "METAL", "WOOD" }, _actionTypes: new List<string>(){ "DEFENSE", "DEFENSE", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""FORMATION_DEFENSE"",""basicValueExpression"":""0.75""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""ARMOUR_DEFENSE"",""basicValueExpression"":""0.75""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DISCIPLINE"",""basicValueExpression"":""1""}" }, _description: "Gain 1/1.2/1.5 Line Defense and 1/1.2/1.5 Armor Defense; Discipline is increased by 1/1.2/1.5. ", _faceimage: "tactic_0036")},
		{"tactic_0037", new Data(_id: "tactic_0037", _ifSpecial: true, _name: "Stacked Woods", _cost: -1, _element: new List<string>(){ "WOOD", "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""DISCARD_CARD"",""basicValueExpression"":""20""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DRAW_WOOD_CARD"",""basicValueExpression"":""REMAINING_ACTION_POINT*1""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""PROJECTILE_ATTACK"",""basicValueExpression"":""WOOD_CARD_NUMBER*1""}" }, _description: "Discard all non-Wood element hand cards, gain X Wood  trigger attack causing 1* number of wood card", _faceimage: "tactic_0037")},
		{"tactic_0038", new Data(_id: "tactic_0038", _ifSpecial: true, _name: "Do-or-Die", _cost: 2, _element: new List<string>(){ "WATER", "WOOD" }, _actionTypes: new List<string>(){ "MODIFIER", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""COUNTERATTACK_MODIFIER"",""basicValueExpression"":""6""}", @"{""from"":""ALL_FRIEND"", ""target"":""CENTER_ENEMY"",""effect"":""PROJECTILE_ATTACK"",""basicValueExpression"":""3""}" }, _description: "Deal 4/5/6 projectile Damage to the enemy center; this turn\'s defensive counterattack effect is increased by 40%/50%/60%.", _faceimage: "tactic_0038")},
		{"tactic_0039", new Data(_id: "tactic_0039", _ifSpecial: true, _name: "Fuel the Fire", _cost: 2, _element: new List<string>(){ "FIRE", "WOOD" }, _actionTypes: new List<string>(){ "DEFENSE", "MODIFIER", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""FORMATION_DEFENSE"",""basicValueExpression"":""2""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""INHERIT_ALL_DEFENSE"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""MORAL"",""basicValueExpression"":""2""}" }, _description: "Gain 2/2.5/3 Line Defense, which carries over to the next game; Morale is increased by 2/2.5/3.", _faceimage: "tactic_0039")},
		{"tactic_0040", new Data(_id: "tactic_0040", _ifSpecial: true, _name: "Wooden Constructs", _cost: 3, _element: new List<string>(){ "EARTH", "WOOD" }, _actionTypes: new List<string>(){ "DEFENSE", "MODIFIER", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""FORMATION_DEFENSE"",""basicValueExpression"":""4""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""MORAL"",""basicValueExpression"":""EARTH_CARD_NUMBER*0.5""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DISCIPLINE"",""basicValueExpression"":""EARTH_CARD_NUMBER*0.5""}" }, _description: "Gain 6/7.5/9 Line Defense; for each Earth element card in hand, increase Morale and Discipline by 1/1.2/1.5.", _faceimage: "tactic_0040")},
		{"tactic_0041", new Data(_id: "tactic_0041", _ifSpecial: false, _name: "Sustained Strike", _cost: 2, _element: new List<string>(){ "METAL" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_AFTER_TURN"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""REDUCE_COST_BY_1"",""basicValueExpression"":""20""}" }, _description: "Reduce the cost of all tactic cards with original costs of 3/2/1 by 1 point next turn.", _faceimage: "tactic_0041")},
		{"tactic_0042", new Data(_id: "tactic_0042", _ifSpecial: false, _name: "Floating Bridge", _cost: 2, _element: new List<string>(){ "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""MORAL_DAMAGE_MODIFIER"",""basicValueExpression"":""6""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DISCIPLINE_DAMAGE_MODIFIER"",""basicValueExpression"":""6""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""DEFENSE_DAMAGE_MODIFIER"",""basicValueExpression"":""6""}" }, _description: "Ignore Terrain and Fortification Defenses this game, deal 2/2.3/3 Damage to enemy fortifications and terrain defenses.", _faceimage: "tactic_0042")},
		{"tactic_0043", new Data(_id: "tactic_0043", _ifSpecial: false, _name: "Quick Rescue", _cost: 1, _element: new List<string>(){ "WATER" }, _actionTypes: new List<string>(){ "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""HEAL_AFTER_BATTLE"",""basicValueExpression"":""1""}" }, _description: "All damage taken this game will be healed by 20%/25%/30% in the next game.", _faceimage: "tactic_0043")},
		{"tactic_0044", new Data(_id: "tactic_0044", _ifSpecial: false, _name: "Blitz Demolition", _cost: 3, _element: new List<string>(){ "FIRE" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL", "ATTACK" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_AFTER_TURN"",""basicValueExpression"":""3""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""IGNORE_DEFENSE"",""basicValueExpression"":""1""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_ENEMY"",""effect"":""SIEGE_ATTACK"",""basicValueExpression"":""9""}" }, _description: "After three rounds, deal 8/10/12 Siege Damage to the enemy, ignoring and removing all enemy defenses; the enemy cannot gain defenses for one round.", _faceimage: "tactic_0044")},
		{"tactic_0045", new Data(_id: "tactic_0045", _ifSpecial: false, _name: "Barricade Setup", _cost: 1, _element: new List<string>(){ "EARTH" }, _actionTypes: new List<string>(){ "DEFENSE", "DEFENSE" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""FORTIFICATION_DEFENSE"",""basicValueExpression"":""EARTH_CARD_PLAYED""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""TERRAIN_DEFENSE"",""basicValueExpression"":""EARTH_CARD_PLAYED""}" }, _description: "Gain 1 Fortification Defense and 1 Terrain Defense per earth card played.", _faceimage: "tactic_0045")},
		{"tactic_0046", new Data(_id: "tactic_0046", _ifSpecial: true, _name: "Forged and Tempered", _cost: 2, _element: new List<string>(){ "METAL", "EARTH" }, _actionTypes: new List<string>(){ "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_POINT_NEXT_TURN"",""basicValueExpression"":""METAL_CARD_PLAYED""}" }, _description: "For each Metal element card played, gain corresponding extra action points next game.", _faceimage: "tactic_0046")},
		{"tactic_0047", new Data(_id: "tactic_0047", _ifSpecial: true, _name: "Mystic Escape", _cost: 3, _element: new List<string>(){ "WOOD", "EARTH" }, _actionTypes: new List<string>(){ "DEFENSE", "DEFENSE", "DEFENSE" }, _functions: new List<string>(){ @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""FORTIFICATION_DEFENSE"",""basicValueExpression"":""2""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""TERRAIN_DEFENSE"",""basicValueExpression"":""2""}", @"{""from"":""ALL_FRIEND"", ""target"":""ALL_FRIEND"",""effect"":""FORMATION_DEFENSE"",""basicValueExpression"":""2""}" }, _description: "Gain 2/2.5/3 Defense Fortifications, Terrain Defense, Maneuver Defense, and Formation Defense.", _faceimage: "tactic_0047")},
		{"tactic_0048", new Data(_id: "tactic_0048", _ifSpecial: true, _name: "Move Mountains", _cost: 2, _element: new List<string>(){ "WATER", "EARTH" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DISCARD_CARD"",""basicValueExpression"":""2""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DRAW_WATER_CARD"",""basicValueExpression"":""2""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""REDUCE_COST_BY_1"",""basicValueExpression"":""2""}" }, _description: "Choose two hand cards to exchange them for random Water element cards, reduce the corresponding card costs by 1.", _faceimage: "tactic_0048")},
		{"tactic_0049", new Data(_id: "tactic_0049", _ifSpecial: true, _name: "Smoke Screen", _cost: 2, _element: new List<string>(){ "FIRE", "EARTH" }, _actionTypes: new List<string>(){ "SPECIAL", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DISCARD_CARD"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DAMAGE_TAKEN_MODIFIER"",""basicValueExpression"":""FIRE_CARD_NUMBER""}" }, _description: "Discard a card from hand; enemy\'s next turn Projectile and Armor Penetration attack effects are reduced by 10%/12%/15%, increase this effect by 5%/6%/7% each time a Fire element card is played this turn.", _faceimage: "tactic_0049")},
		{"tactic_0050", new Data(_id: "tactic_0050", _ifSpecial: true, _name: "Unified Effort", _cost: -1, _element: new List<string>(){ "EARTH", "EARTH" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_POINT_NEXT_TURN"",""basicValueExpression"":""REMAINING_ACTION_POINT*1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""INHERIT_ALL_DEFENSE"",""basicValueExpression"":""1""}" }, _description: "Consume all remaining action points, retain all defense effects, gain additional action points next game by x/1.2x/1.5x.", _faceimage: "tactic_0050")},
		{"stratagem_0001", new Data(_id: "stratagem_0001", _ifSpecial: true, _name: "Deceive the Sky", _cost: 2, _element: new List<string>(){ "WATER", "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""COPY_TACTIC_CARD"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""REDUCE_COST_BY_2"",""basicValueExpression"":""1""}" }, _description: "Copy the 1 Tactic card and reduce the cost of that card by 2", _faceimage: "stratagem_0001")},
		{"stratagem_0002", new Data(_id: "stratagem_0002", _ifSpecial: true, _name: "Besiege Wei to Rescue Zhao", _cost: 3, _element: new List<string>(){ "FIRE", "EARTH" }, _actionTypes: new List<string>(){ "SPECIAL", "DEFENSE" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_WHEN_ATTACK"",""basicValueExpression"":""5""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""FORTIFICATION_DEFENSE"",""basicValueExpression"":""1""}" }, _description: "Your next 5 attack card played gives you addtional 1 fortified defense", _faceimage: "stratagem_0002")},
		{"stratagem_0003", new Data(_id: "stratagem_0003", _ifSpecial: true, _name: "Counter-spy", _cost: 2, _element: new List<string>(){ "WATER", "FIRE" }, _actionTypes: new List<string>(){ "SPECIAL", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""ACTION_WHEN_STRATEGY"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""ACTION_POINT_NEXT_TURN"",""basicValueExpression"":""2""}" }, _description: "Enemy\'s Next 1 Strategy Fails", _faceimage: "stratagem_0003")},
		{"stratagem_0004", new Data(_id: "stratagem_0004", _ifSpecial: true, _name: "Self-hurt", _cost: 2, _element: new List<string>(){ "FIRE", "EARTH" }, _actionTypes: new List<string>(){ "SPECIAL", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""ACTION_WHEN_TACTIC"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""DRAW_CARD_NEXT_TURN"",""basicValueExpression"":""4""}" }, _description: "Enemy\'s Next 1 Tactic Fails", _faceimage: "stratagem_0004")},
		{"stratagem_0005", new Data(_id: "stratagem_0005", _ifSpecial: true, _name: "Loot a Burning House", _cost: 1, _element: new List<string>(){ "FIRE", "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_WHEN_ATTACK"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DISCIPLINE_DAMAGE_MODIFIER"",""basicValueExpression"":""3""}" }, _description: "Next Tactical Attack Deals 2/3/4 Times Discipline Damage", _faceimage: "stratagem_0005")},
		{"stratagem_0006", new Data(_id: "stratagem_0006", _ifSpecial: true, _name: "Opportunism", _cost: 1, _element: new List<string>(){ "WOOD", "METAL" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""GAIN_TACTIC_CARD"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""REDUCE_COST_BY_2"",""basicValueExpression"":""9""}" }, _description: " Gain a Random Strategy Card, Use It Without Cost", _faceimage: "stratagem_0006")},
		{"stratagem_0007", new Data(_id: "stratagem_0007", _ifSpecial: true, _name: "Beauty Trap", _cost: 1, _element: new List<string>(){ "METAL", "WATER" }, _actionTypes: new List<string>(){ "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""ACTION_POINT_NEXT_TURN"",""basicValueExpression"":""-2""}" }, _description: "Consume 1/2/3 of the Opponent\'s Action Points", _faceimage: "stratagem_0007")},
		{"stratagem_0008", new Data(_id: "stratagem_0008", _ifSpecial: true, _name: "Empty Fort", _cost: 1, _element: new List<string>(){ "EARTH", "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""ACTION_WHEN_ATTACK"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""MORAL"",""basicValueExpression"":""-2""}" }, _description: "Enemy\'s first attack action reduce the enemy\'s moral by 2", _faceimage: "stratagem_0008")},
		{"stratagem_0009", new Data(_id: "stratagem_0009", _ifSpecial: true, _name: "Feign Madness", _cost: 2, _element: new List<string>(){ "WATER", "FIRE" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_WHEN_ATTACK"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DISCIPLINE_MULTIPLIER"",""basicValueExpression"":""2""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""MORAL_MULTIPLIER"",""basicValueExpression"":""2""}" }, _description: "Next Turn, Morale and Discipline *2", _faceimage: "stratagem_0009")},
		{"stratagem_0010", new Data(_id: "stratagem_0010", _ifSpecial: true, _name: "Rest While Enemy Labors", _cost: 3, _element: new List<string>(){ "EARTH", "WATER" }, _actionTypes: new List<string>(){ "SPECIAL", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_WHEN_ATTACK"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""MORAL"",""basicValueExpression"":""-1""}" }, _description: "Enemy\'s Attacks on Allies Next Turn Will Consume 1/1.5/2 Enemy Morale", _faceimage: "stratagem_0010")},
		{"stratagem_0011", new Data(_id: "stratagem_0011", _ifSpecial: true, _name: "Lure with Brick", _cost: 1, _element: new List<string>(){ "WOOD", "FIRE" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""GAIN_STRATEGY_CARD"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""REDUCE_COST_BY_2"",""basicValueExpression"":""9""}" }, _description: "Upgrade a Random Strategy Card in Hand by 0/1/2 Levels, Reduce Cost by 3/2/1", _faceimage: "stratagem_0011")},
		{"stratagem_0012", new Data(_id: "stratagem_0012", _ifSpecial: true, _name: "East-wind Attack", _cost: 1, _element: new List<string>(){ "FIRE", "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""GAIN_STRATEGY_CARD"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""REDUCE_COST_BY_2"",""basicValueExpression"":""9""}" }, _description: "Gain 1/2/3 Random Strategy Cards", _faceimage: "stratagem_0012")},
		{"stratagem_0013", new Data(_id: "stratagem_0013", _ifSpecial: true, _name: "Substitute Beams", _cost: 1, _element: new List<string>(){ "WOOD", "METAL" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DISCARD_CARD"",""basicValueExpression"":""20""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DRAW_CARD"",""basicValueExpression"":""6""}" }, _description: "Discard All Cards, Then Draw 3/6/9 New Cards", _faceimage: "stratagem_0013")},
		{"stratagem_0014", new Data(_id: "stratagem_0014", _ifSpecial: true, _name: "Indirect Scold", _cost: 2, _element: new List<string>(){ "EARTH", "FIRE" }, _actionTypes: new List<string>(){ "MODIFIER", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""MORAL"",""basicValueExpression"":""-2""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DISCIPLINE"",""basicValueExpression"":""+6""}" }, _description: "Moral -2, Discipline +6", _faceimage: "stratagem_0014")},
		{"stratagem_0015", new Data(_id: "stratagem_0015", _ifSpecial: true, _name: "Borrowed Knife", _cost: 1, _element: new List<string>(){ "METAL", "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""GAIN_STRATEGY_CARD"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""REDUCE_COST_BY_2"",""basicValueExpression"":""9""}" }, _description: "Gain a Random 1/2/3 Cost Tactical Card, Use It Without Action Points", _faceimage: "stratagem_0015")},
		{"stratagem_0016", new Data(_id: "stratagem_0016", _ifSpecial: true, _name: "Remove Ladder", _cost: 2, _element: new List<string>(){ "EARTH", "FIRE" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""ACTION_WHEN_STRATEGY"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_POINT"",""basicValueExpression"":""-2""}" }, _description: "After the Enemy Uses Their Next Strategy, They Cannot Use Tactical Cards and Lose 1/2/3 Action Points", _faceimage: "stratagem_0016")},
		{"stratagem_0017", new Data(_id: "stratagem_0017", _ifSpecial: true, _name: "Distant Friends", _cost: 3, _element: new List<string>(){ "WOOD", "EARTH" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""ACTION_POINT_NEXT_TURN"",""basicValueExpression"":""-3""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_POINT_NEXT_TURN"",""basicValueExpression"":""3""}" }, _description: "Gain 2/2.5/3 Morale and Discipline", _faceimage: "stratagem_0017")},
		{"stratagem_0018", new Data(_id: "stratagem_0018", _ifSpecial: true, _name: "Best Retreat", _cost: 1, _element: new List<string>(){ "WATER", "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""INHERIT_ALL_ACTION_POINT"",""basicValueExpression"":""3""}" }, _description: "Your Action Points Can be Inherited over 3 Turns.", _faceimage: "stratagem_0018")},
		{"stratagem_0019", new Data(_id: "stratagem_0019", _ifSpecial: true, _name: "Create Illusion", _cost: -1, _element: new List<string>(){ "FIRE", "WATER" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DRAW_CARD_NEXT_TURN"",""basicValueExpression"":""REMAINING_ACTION_POINT""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""REDUCE_COST_BY_1"",""basicValueExpression"":""REMAINING_ACTION_POINT""}" }, _description: "Next Turn, Gain X Cards with Their Costs Reduced by 1/2/3", _faceimage: "stratagem_0019")},
		{"stratagem_0020", new Data(_id: "stratagem_0020", _ifSpecial: true, _name: "Fish in Troubled Water", _cost: 2, _element: new List<string>(){ "WATER", "WATER" }, _actionTypes: new List<string>(){ "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""DISCIPLINE"",""basicValueExpression"":""WATER_CARD_NUMBER""}" }, _description: "Enemy Discipline Decreased per Water Card in Your Hand.", _faceimage: "stratagem_0020")},
		{"stratagem_0021", new Data(_id: "stratagem_0021", _ifSpecial: true, _name: "Escape Shell", _cost: 2, _element: new List<string>(){ "WOOD", "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""ACTION_POINT"",""basicValueExpression"":""WOOD_CARD_NUMBER""}" }, _description: "Gain Action Points per Wood Card  in Your Hand.", _faceimage: "stratagem_0021")},
		{"stratagem_0022", new Data(_id: "stratagem_0022", _ifSpecial: true, _name: "Close Door to Catch Thief", _cost: 3, _element: new List<string>(){ "FIRE", "FIRE" }, _actionTypes: new List<string>(){ "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""DAMAGE_TAKEN_MODIFIER"",""basicValueExpression"":""FIRE_CARD_NUMBER""}" }, _description: "Your Enemy taken extra damage by 20%* Fire Cards in Your Hand", _faceimage: "stratagem_0022")},
		{"stratagem_0023", new Data(_id: "stratagem_0023", _ifSpecial: true, _name: "False Growth", _cost: 3, _element: new List<string>(){ "WOOD", "WOOD" }, _actionTypes: new List<string>(){ "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""COUNTERATTACK_MODIFIER"",""basicValueExpression"":""WOOD_CARD_NUMBER""}" }, _description: "Your Counterattack Effect Increased by 20%* Fire Cards in Your Hand", _faceimage: "stratagem_0023")},
		{"stratagem_0024", new Data(_id: "stratagem_0024", _ifSpecial: true, _name: "Turn Guest to Host", _cost: 1, _element: new List<string>(){ "EARTH", "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""ACTION_WHEN_STRATEGY"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""BURN_CARD"",""basicValueExpression"":""2""}" }, _description: "Enemy\'s Next Strategy  card played burn 2 random card.", _faceimage: "stratagem_0024")},
		{"stratagem_0025", new Data(_id: "stratagem_0025", _ifSpecial: true, _name: "Startle Snake", _cost: 1, _element: new List<string>(){ "FIRE", "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""ACTION_WHEN_ATTACK"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""BURN_CARD"",""basicValueExpression"":""2""}" }, _description: "Enemy\'s Next ATTACK  card played burn 2 random card.", _faceimage: "stratagem_0025")},
		{"stratagem_0026", new Data(_id: "stratagem_0026", _ifSpecial: true, _name: "Secret Path", _cost: 2, _element: new List<string>(){ "EARTH", "EARTH" }, _actionTypes: new List<string>(){ "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_POINT"",""basicValueExpression"":""EARTH_CARD_NUMBER""}" }, _description: "Increase Action Points this Turn by Earth Cards in Your Hand.", _faceimage: "stratagem_0026")},
		{"stratagem_0027", new Data(_id: "stratagem_0027", _ifSpecial: true, _name: "Watch Fire from Shore", _cost: 3, _element: new List<string>(){ "FIRE", "WATER" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""DISCIPLINE_MULTIPLIER"",""basicValueExpression"":""2""}", @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""MORAL_MULTIPLIER"",""basicValueExpression"":""2""}" }, _description: "ENEMY Moral and Discipline multpilied by 2", _faceimage: "stratagem_0027")},
		{"stratagem_0028", new Data(_id: "stratagem_0028", _ifSpecial: true, _name: "Release to Catch", _cost: 3, _element: new List<string>(){ "WATER", "WATER" }, _actionTypes: new List<string>(){ "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""ACTION_POINT_NEXT_TURN"",""basicValueExpression"":""WATER_CARD_NUMBER""}" }, _description: "Gain 3/4/5 Extra Action Points Next Turn", _faceimage: "stratagem_0028")},
		{"stratagem_0029", new Data(_id: "stratagem_0029", _ifSpecial: true, _name: "Linked Strategy", _cost: 1, _element: new List<string>(){ "WOOD", "EARTH" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""COPY_STRATEGY_CARD"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""REDUCE_COST_BY_3"",""basicValueExpression"":""1""}" }, _description: "Copy a Strategy Card in your Hand make it free", _faceimage: "stratagem_0029")},
		{"stratagem_0030", new Data(_id: "stratagem_0030", _ifSpecial: true, _name: "Borrow Route", _cost: 2, _element: new List<string>(){ "WOOD", "FIRE" }, _actionTypes: new List<string>(){ "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""IGNORE_DEFENSE"",""basicValueExpression"":""2""}" }, _description: "Next 2 Attacks Ignore All Enemy Defense", _faceimage: "stratagem_0030")},
		{"stratagem_0031", new Data(_id: "stratagem_0031", _ifSpecial: true, _name: "Undermine", _cost: 2, _element: new List<string>(){ "WATER", "EARTH" }, _actionTypes: new List<string>(){ "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""CENTER_ENEMY"",""effect"":""DAMAGE_TAKEN_MODIFIER"",""basicValueExpression"":""6""}" }, _description: "Next Attack Directly Hits Enemy Rear", _faceimage: "stratagem_0031")},
		{"stratagem_0032", new Data(_id: "stratagem_0032", _ifSpecial: true, _name: "Fake Revival", _cost: 1, _element: new List<string>(){ "WATER", "WOOD" }, _actionTypes: new List<string>(){ "SPECIAL", "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DRAW_WOOD_CARD_NEXT_TURN"",""basicValueExpression"":""1""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DRAW_WATER_CARD_NEXT_TURN"",""basicValueExpression"":""1""}" }, _description: "Gain 1 Extra wood and water cards next turn", _faceimage: "stratagem_0032")},
		{"stratagem_0033", new Data(_id: "stratagem_0033", _ifSpecial: true, _name: "Lure Tiger Away", _cost: 2, _element: new List<string>(){ "FIRE", "WOOD" }, _actionTypes: new List<string>(){ "MODIFIER" }, _description: "Enemy\'s Tactical Card Effects Reduced by 20%/30%/40% Next Round", _faceimage: "stratagem_0033")},
		{"stratagem_0034", new Data(_id: "stratagem_0034", _ifSpecial: true, _name: "Hidden Knife", _cost: 2, _element: new List<string>(){ "METAL", "METAL" }, _actionTypes: new List<string>(){ "MODIFIER", "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""MORAL_DAMAGE_MODIFIER"",""basicValueExpression"":""METAL_CARD_NUMBER""}", @"{""from"":""NONE"", ""target"":""ALL_FRIEND"",""effect"":""DISCIPLINE_DAMAGE_MODIFIER"",""basicValueExpression"":""METAL_CARD_NUMBER""}" }, _description: "Next Strategy Card Will Be Used Twice", _faceimage: "stratagem_0034")},
		{"stratagem_0035", new Data(_id: "stratagem_0035", _ifSpecial: true, _name: "Substitute", _cost: 2, _element: new List<string>(){ "METAL", "WOOD" }, _actionTypes: new List<string>(){ "MODIFIER" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""MORAL_DAMAGE_MODIFIER"",""basicValueExpression"":""-2""}", @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""DISCIPLINE_DAMAGE_MODIFIER"",""basicValueExpression"":""-2""}" }, _description: "Next Turn, Damage is Taken by the Unit with the Highest Armor and Best Condition", _faceimage: "stratagem_0035")},
		{"stratagem_0036", new Data(_id: "stratagem_0036", _ifSpecial: true, _name: "Catch Leader", _cost: 1, _element: new List<string>(){ "EARTH", "FIRE" }, _actionTypes: new List<string>(){ "SPECIAL" }, _functions: new List<string>(){ @"{""from"":""NONE"", ""target"":""ALL_ENEMY"",""effect"":""DRAW_CARD_NEXT_TURN"",""basicValueExpression"":""-3""}" }, _description: "Enemy Draws 3 Fewer Cards Next Round", _faceimage: "stratagem_0036")},
	};
}
