//#file：./tab/unit.xlsx, sheet：unit，output：unit.cs

using System.Collections.Generic;

public class Table_unit
{
	public struct Data
	{
		public string id;
		public string name;
		public int level;
		public string group;
		public string culture;
		public string age;
		public float basicEquipment;
		public float basicTraining;
		public float basicMoral;
		public float basicDiscipline;
		public List<string> attackType;
		public List<string> defenseType;
		public string meleeType;
		public string rangedType;
		public string armourType;
		public string mountedType;
		public float priotizedAttack;
		public float meleeAttack;
		public float projectileAttack;
		public float armorPiercingAttack;
		public float siegeAttack;
		public int range;
		public float terrainDefense;
		public float fortificationDefense;
		public float elasticDefense;
		public float formationDefense;
		public float armourDefense;
		public List<string> ability;
		public string description;
		public string faceimage;
		public string backImage;
		public List<float> faceCenter;
		public string voiceActing;

		public Data(string _id = "", string _name = "", int _level = 0, string _group = "", string _culture = "", string _age = "", float _basicEquipment = 0.0f, float _basicTraining = 0.0f, float _basicMoral = 0.0f, float _basicDiscipline = 0.0f, List<string> _attackType = null, List<string> _defenseType = null, string _meleeType = "", string _rangedType = "", string _armourType = "", string _mountedType = "", float _priotizedAttack = 0.0f, float _meleeAttack = 0.0f, float _projectileAttack = 0.0f, float _armorPiercingAttack = 0.0f, float _siegeAttack = 0.0f, int _range = 0, float _terrainDefense = 0.0f, float _fortificationDefense = 0.0f, float _elasticDefense = 0.0f, float _formationDefense = 0.0f, float _armourDefense = 0.0f, List<string> _ability = null, string _description = "", string _faceimage = "", string _backImage = "", List<float> _faceCenter = null, string _voiceActing = "")
		{
			id = _id;
			name = _name;
			level = _level;
			group = _group;
			culture = _culture;
			age = _age;
			basicEquipment = _basicEquipment;
			basicTraining = _basicTraining;
			basicMoral = _basicMoral;
			basicDiscipline = _basicDiscipline;
			attackType = _attackType;
			defenseType = _defenseType;
			meleeType = _meleeType;
			rangedType = _rangedType;
			armourType = _armourType;
			mountedType = _mountedType;
			priotizedAttack = _priotizedAttack;
			meleeAttack = _meleeAttack;
			projectileAttack = _projectileAttack;
			armorPiercingAttack = _armorPiercingAttack;
			siegeAttack = _siegeAttack;
			range = _range;
			terrainDefense = _terrainDefense;
			fortificationDefense = _fortificationDefense;
			elasticDefense = _elasticDefense;
			formationDefense = _formationDefense;
			armourDefense = _armourDefense;
			ability = _ability;
			description = _description;
			faceimage = _faceimage;
			backImage = _backImage;
			faceCenter = _faceCenter;
			voiceActing = _voiceActing;
		}
	}
	public static Dictionary<string, Data> data = new Dictionary<string, Data> {
		{"unit_0001", new Data(_id: "unit_0001", _name: "Javelineer", _level: 1, _group: "PROJECTILE", _culture: "maya", _age: "stone", _basicEquipment: 1.0f, _basicTraining: 1.0f, _basicMoral: 0.0f, _basicDiscipline: 0.0f, _attackType: new List<string>(){ "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "Javelin", _armourType: "NaN", _mountedType: "NaN", _priotizedAttack: 0.0f, _meleeAttack: 0.0f, _projectileAttack: 1.0f, _range: 2, _fortificationDefense: 0.0f, _elasticDefense: 1.2f, _ability: new List<string>(){ "jungleFighter", "slaveTrader" }, _description: "NaN", _faceimage: "unit_0001", _backImage: "card_unit_back", _faceCenter: new List<float>(){ 0.5f, 0.8f })},
		{"unit_0002", new Data(_id: "unit_0002", _name: "HandBallista Unit", _level: 2, _group: "SIEGE", _culture: "rome", _age: "iron", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "projectile", "siege" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "crossbow", _armourType: "leather", _mountedType: "NaN", _priotizedAttack: 0.0f, _meleeAttack: 0.0f, _projectileAttack: 1.2f, _armorPiercingAttack: 1.2f, _siegeAttack: 1.0f, _range: 2, _elasticDefense: 1.0f, _ability: new List<string>(){ "professional", "mecanic" }, _faceimage: "unit_0002", _backImage: "card_unit_back", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0003", new Data(_id: "unit_0003", _name: "Repeating Crossbow Man", _level: 1, _group: "PROJECTILE", _culture: "china", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "crossbow", _armourType: "leather", _mountedType: "NaN", _priotizedAttack: 0.0f, _meleeAttack: 0.0f, _projectileAttack: 1.2f, _armorPiercingAttack: 0.0f, _siegeAttack: 0.0f, _range: 1, _elasticDefense: 1.2f, _ability: new List<string>(){ "repeatingFire", "mecanic" }, _faceimage: "unit_0003", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0004", new Data(_id: "unit_0004", _name: "Greek Flame Thrower", _level: 3, _group: "FIREARM", _culture: "byzantin", _age: "fire", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "projectile", "siege" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "flameThrower", _armourType: "leather", _mountedType: "NaN", _projectileAttack: 0.0f, _armorPiercingAttack: 1.8f, _siegeAttack: 1.8f, _range: 1, _elasticDefense: 1.0f, _ability: new List<string>(){ "fireArm" }, _faceimage: "unit_0004", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0005", new Data(_id: "unit_0005", _name: "Genoese Crossbowmen", _level: 3, _group: "PROJECTILE", _culture: "europe", _age: "iron", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "crossbow", _armourType: "metal", _mountedType: "NaN", _projectileAttack: 1.4f, _armorPiercingAttack: 1.4f, _siegeAttack: 0.0f, _range: 2, _elasticDefense: 1.0f, _armourDefense: 1.0f, _ability: new List<string>(){ "professional", "mercenery", "mecanic" }, _faceimage: "unit_0005", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0006", new Data(_id: "unit_0006", _name: "Huochong Unit", _level: 2, _group: "FIREARM", _culture: "china", _age: "fire", _basicEquipment: 2.0f, _basicTraining: 1.0f, _attackType: new List<string>(){ "projectile", "siege" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "fireArm", _armourType: "leather", _mountedType: "NaN", _projectileAttack: 1.4f, _armorPiercingAttack: 1.4f, _siegeAttack: 1.4f, _range: 2, _elasticDefense: 1.0f, _ability: new List<string>(){ "fireArrm" }, _faceimage: "unit_0006", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0007", new Data(_id: "unit_0007", _name: "Hand Gun Samurai", _level: 3, _group: "FIREARM", _culture: "japan", _age: "fire", _basicEquipment: 3.0f, _basicTraining: 4.0f, _attackType: new List<string>(){ "projectile", "siege" }, _defenseType: new List<string>(){ "elastic", "armour" }, _meleeType: "NaN", _rangedType: "fireArm", _armourType: "metal", _mountedType: "NaN", _projectileAttack: 1.8f, _armorPiercingAttack: 1.8f, _siegeAttack: 1.8f, _range: 2, _elasticDefense: 1.0f, _armourDefense: 0.5f, _ability: new List<string>(){ "fireArrm", "samurai" }, _faceimage: "unit_0007", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0008", new Data(_id: "unit_0008", _name: "Conquistador", _level: 4, _group: "FIREARM", _culture: "eurpoe", _age: "fire", _basicEquipment: 4.0f, _basicTraining: 4.0f, _attackType: new List<string>(){ "projectile" }, _defenseType: new List<string>(){ "elastic", "armour" }, _meleeType: "NaN", _rangedType: "fireArm", _armourType: "metal", _mountedType: "NaN", _projectileAttack: 2.0f, _armorPiercingAttack: 2.0f, _siegeAttack: 0.0f, _range: 2, _elasticDefense: 1.0f, _armourDefense: 1.0f, _ability: new List<string>(){ "fireArrm" }, _faceimage: "unit_0008", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0009", new Data(_id: "unit_0009", _name: "Musketeer Militia", _level: 1, _group: "FIREARM", _culture: "china", _age: "fire", _basicEquipment: 1.0f, _basicTraining: 1.0f, _attackType: new List<string>(){ "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "fireArm", _armourType: "NaN", _mountedType: "NaN", _projectileAttack: 1.4f, _armorPiercingAttack: 1.4f, _siegeAttack: 0.0f, _range: 2, _elasticDefense: 1.0f, _ability: new List<string>(){ "fireArrm", "milica" }, _faceimage: "unit_0009", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0010", new Data(_id: "unit_0010", _name: "Polynesian Head Hunter", _level: 2, _group: "FIREARM", _culture: "polynesia", _age: "fire", _basicEquipment: 1.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "fireArm", _armourType: "NaN", _mountedType: "NaN", _projectileAttack: 1.5f, _armorPiercingAttack: 1.5f, _range: 2, _elasticDefense: 1.6f, _ability: new List<string>(){ "jungleFighter", "skirmish" }, _faceimage: "unit_0010", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0011", new Data(_id: "unit_0011", _name: "Flintlock Musketeer", _level: 3, _group: "FIREARM", _culture: "china", _age: "fire", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "fireArm", _armourType: "NaN", _mountedType: "NaN", _projectileAttack: 1.7f, _armorPiercingAttack: 1.7f, _siegeAttack: 0.0f, _range: 2, _elasticDefense: 1.0f, _ability: new List<string>(){ "fireArrm" }, _faceimage: "unit_0011", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0012", new Data(_id: "unit_0012", _name: "Rifle Skirmisher", _level: 4, _group: "FIREARM", _culture: "semitic", _age: "fire", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "fireArm", _armourType: "NaN", _mountedType: "NaN", _projectileAttack: 2.0f, _armorPiercingAttack: 2.0f, _range: 3, _elasticDefense: 2.0f, _ability: new List<string>(){ "fireArrm" }, _faceimage: "unit_0012", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0013", new Data(_id: "unit_0013", _name: "Sling Thrower", _level: 1, _group: "PROJECTILE", _culture: "semitic", _age: "stone", _basicEquipment: 1.0f, _basicTraining: 1.0f, _attackType: new List<string>(){ "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "sling", _armourType: "NaN", _mountedType: "NaN", _projectileAttack: 1.2f, _elasticDefense: 1.6f, _ability: new List<string>(){ "skirmish" }, _faceimage: "unit_0013", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0014", new Data(_id: "unit_0014", _name: "Jaguar Warrior", _level: 1, _group: "PROJECTILE", _culture: "china", _age: "stone", _basicEquipment: 1.0f, _basicTraining: 1.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "elastic", "formation" }, _meleeType: "stoneAxe", _rangedType: "NaN", _armourType: "NaN", _mountedType: "NaN", _priotizedAttack: 0.4f, _meleeAttack: 1.0f, _elasticDefense: 1.0f, _formationDefense: 0.5f, _ability: new List<string>(){ "jungleFighter", "slaveTrader" }, _faceimage: "unit_0014", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0015", new Data(_id: "unit_0015", _name: "Mozi\'s Disciple", _level: 4, _group: "PROJECTILE", _culture: "china", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 5.0f, _attackType: new List<string>(){ "melee", "charge", "projectile" }, _defenseType: new List<string>(){ "elastic", "formation" }, _meleeType: "ironSword", _rangedType: "crossbow", _armourType: "leather", _mountedType: "NaN", _priotizedAttack: 1.0f, _meleeAttack: 2.0f, _projectileAttack: 1.4f, _range: 2, _elasticDefense: 1.6f, _formationDefense: 0.5f, _faceimage: "unit_0015", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0016", new Data(_id: "unit_0016", _name: "Composite Bowman", _level: 2, _group: "PROJECTILE", _culture: "india", _age: "iron", _basicEquipment: 1.0f, _basicTraining: 1.0f, _attackType: new List<string>(){ "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "bow", _armourType: "leather", _mountedType: "NaN", _projectileAttack: 1.3f, _range: 2, _elasticDefense: 1.0f, _faceimage: "unit_0016", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0017", new Data(_id: "unit_0017", _name: "long Bowman", _level: 3, _group: "PROJECTILE", _culture: "europe", _age: "iron", _basicEquipment: 1.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "NaN", _rangedType: "bow", _armourType: "leather", _mountedType: "NaN", _projectileAttack: 1.5f, _range: 3, _elasticDefense: 1.0f, _faceimage: "unit_0017", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0018", new Data(_id: "unit_0018", _name: "Militia", _level: 1, _group: "SPEAR", _culture: "china", _age: "iron", _basicEquipment: 1.0f, _basicTraining: 1.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "formation" }, _meleeType: "ironSpear", _rangedType: "NaN", _armourType: "NaN", _mountedType: "NaN", _priotizedAttack: 0.7f, _meleeAttack: 0.7f, _siegeAttack: 0.0f, _formationDefense: 1.0f, _ability: new List<string>(){ "milica" }, _faceimage: "unit_0018", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0019", new Data(_id: "unit_0019", _name: "Imperial Palace Guard", _level: 3, _group: "SPEAR", _culture: "china", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "formation" }, _meleeType: "ironSpear", _rangedType: "NaN", _armourType: "NaN", _mountedType: "NaN", _priotizedAttack: 1.2f, _meleeAttack: 1.0f, _projectileAttack: 0.5f, _formationDefense: 1.2f, _faceimage: "unit_0019", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0020", new Data(_id: "unit_0020", _name: "Celtic Warrior", _level: 2, _group: "MELEE", _culture: "europe", _age: "iron", _basicEquipment: 1.0f, _basicTraining: 1.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "elastic", "formation" }, _meleeType: "ironSword", _rangedType: "NaN", _armourType: "NaN", _mountedType: "NaN", _priotizedAttack: 1.0f, _meleeAttack: 1.0f, _elasticDefense: 1.0f, _formationDefense: 0.5f, _faceimage: "unit_0020", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0021", new Data(_id: "unit_0021", _name: "Bandit", _level: 2, _group: "PROJECTILE", _culture: "europe", _age: "iron", _basicEquipment: 1.0f, _basicTraining: 1.0f, _attackType: new List<string>(){ "melee", "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "ironSpear", _rangedType: "bow", _armourType: "metal", _mountedType: "NaN", _priotizedAttack: 1.2f, _meleeAttack: 1.0f, _projectileAttack: 1.0f, _range: 2, _elasticDefense: 1.0f, _faceimage: "unit_0021", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0022", new Data(_id: "unit_0022", _name: "Warrior Monk", _level: 3, _group: "SPEAR", _culture: "korea", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "elastic", "formation" }, _meleeType: "ironSpear", _rangedType: "NaN", _armourType: "metal", _mountedType: "NaN", _priotizedAttack: 1.3f, _meleeAttack: 1.3f, _elasticDefense: 1.0f, _formationDefense: 1.0f, _armourDefense: 0.5f, _faceimage: "unit_0022", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0023", new Data(_id: "unit_0023", _name: "Qi Army", _level: 2, _group: "SPEAR", _culture: "china", _age: "iron", _basicEquipment: 1.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "elastic", "formation" }, _meleeType: "ironSpear", _rangedType: "NaN", _armourType: "metal", _mountedType: "NaN", _priotizedAttack: 1.2f, _meleeAttack: 1.0f, _elasticDefense: 1.0f, _formationDefense: 1.4f, _faceimage: "unit_0023", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0024", new Data(_id: "unit_0024", _name: "Samurai", _level: 3, _group: "MELEE", _culture: "japan", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "elastic", "formation", "armour" }, _meleeType: "ironSword", _rangedType: "NaN", _armourType: "metal", _mountedType: "NaN", _priotizedAttack: 1.0f, _meleeAttack: 1.4f, _elasticDefense: 1.0f, _formationDefense: 0.5f, _armourDefense: 0.5f, _faceimage: "unit_0024", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0025", new Data(_id: "unit_0025", _name: "Hoplite", _level: 3, _group: "HEAVY", _culture: "europe", _age: "bronze", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee" }, _defenseType: new List<string>(){ "formation", "armour" }, _meleeType: "ironSpear", _rangedType: "NaN", _armourType: "metal", _mountedType: "NaN", _priotizedAttack: 1.2f, _meleeAttack: 1.0f, _formationDefense: 2.0f, _armourDefense: 2.0f, _faceimage: "unit_0025", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0026", new Data(_id: "unit_0026", _name: "Legionary", _level: 3, _group: "HEAVY", _culture: "europe", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee", "charge", "projectile" }, _defenseType: new List<string>(){ "formation", "armour" }, _meleeType: "ironSword", _rangedType: "javelin", _armourType: "metal", _mountedType: "NaN", _priotizedAttack: 0.8f, _meleeAttack: 1.0f, _projectileAttack: 1.0f, _range: 1, _formationDefense: 1.7f, _armourDefense: 1.7f, _faceimage: "unit_0026", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0027", new Data(_id: "unit_0027", _name: "Wei Warrior", _level: 3, _group: "HEAVY", _culture: "china", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "formation", "armour" }, _meleeType: "ironSword", _rangedType: "NaN", _armourType: "metal", _mountedType: "NaN", _priotizedAttack: 0.8f, _meleeAttack: 1.5f, _formationDefense: 1.5f, _armourDefense: 1.5f, _faceimage: "unit_0027", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0028", new Data(_id: "unit_0028", _name: "Immortal", _level: 3, _group: "HEAVY", _culture: "perse", _age: "bronze", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee", "charge", "projectile" }, _defenseType: new List<string>(){ "formation", "armour" }, _meleeType: "ironSpear", _rangedType: "bow", _armourType: "leather", _mountedType: "NaN", _priotizedAttack: 1.2f, _meleeAttack: 1.0f, _projectileAttack: 1.5f, _range: 2, _formationDefense: 1.5f, _armourDefense: 1.5f, _faceimage: "unit_0028", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0029", new Data(_id: "unit_0029", _name: "Xian Deng Champion", _level: 4, _group: "HEAVY", _culture: "china", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee", "charge", "projectile" }, _defenseType: new List<string>(){ "formation", "armour" }, _meleeType: "ironSword", _rangedType: "crossbow", _armourType: "metal", _priotizedAttack: 0.8f, _meleeAttack: 1.8f, _projectileAttack: 1.4f, _armorPiercingAttack: 1.4f, _range: 2, _formationDefense: 1.5f, _armourDefense: 1.5f, _faceimage: "unit_0029", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0030", new Data(_id: "unit_0030", _name: "Viking Warrior", _level: 2, _group: "HEAVY", _culture: "europe", _age: "iron", _basicEquipment: 1.5f, _basicTraining: 1.0f, _attackType: new List<string>(){ "melee", "charge", "projectile" }, _defenseType: new List<string>(){ "elastic", "formation", "armour" }, _meleeType: "ironSword", _rangedType: "javelin", _armourType: "leather", _priotizedAttack: 0.8f, _meleeAttack: 1.0f, _projectileAttack: 1.0f, _range: 1, _elasticDefense: 1.0f, _formationDefense: 1.0f, _armourDefense: 1.2f, _faceimage: "unit_0030", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0031", new Data(_id: "unit_0031", _name: "Swiss Mercenary", _level: 3, _group: "HEAVY", _culture: "europe", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee" }, _defenseType: new List<string>(){ "formation", "armour" }, _meleeType: "ironSpear", _armourType: "metal", _priotizedAttack: 1.2f, _meleeAttack: 1.0f, _formationDefense: 1.8f, _armourDefense: 1.8f, _faceimage: "unit_0031", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0032", new Data(_id: "unit_0032", _name: "Tercio", _level: 4, _group: "HEAVY", _culture: "europe", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "melee" }, _defenseType: new List<string>(){ "formation", "armour" }, _meleeType: "ironSpear", _armourType: "metal", _priotizedAttack: 1.2f, _meleeAttack: 1.2f, _formationDefense: 2.0f, _armourDefense: 2.0f, _faceimage: "unit_0032", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0033", new Data(_id: "unit_0033", _name: "Man-at-arms", _level: 4, _group: "HEAVY", _culture: "europe", _age: "iron", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "elastic", "formation", "armour" }, _meleeType: "ironSword", _armourType: "metal", _priotizedAttack: 0.8f, _meleeAttack: 1.6f, _elasticDefense: 1.0f, _formationDefense: 1.0f, _armourDefense: 2.0f, _faceimage: "unit_0033", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_0034", new Data(_id: "unit_0034", _name: "Zulu Warrior", _level: 2, _group: "HEAVY", _culture: "africa", _age: "iron", _basicEquipment: 1.0f, _basicTraining: 1.5f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "formation", "armour" }, _meleeType: "ironSpear", _armourType: "metal", _priotizedAttack: 1.2f, _meleeAttack: 1.2f, _elasticDefense: 1.0f, _formationDefense: 1.2f, _armourDefense: 1.2f, _faceimage: "unit_0034", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5001", new Data(_id: "unit_5001", _name: "Parthia Mounted Archer", _level: 2, _group: "CAVALRY", _culture: "perse", _age: "bronze", _basicEquipment: 1.0f, _basicTraining: 1.0f, _attackType: new List<string>(){ "melee", "charge", "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "ironSword", _rangedType: "bow", _armourType: "NaN", _mountedType: "horse", _priotizedAttack: 0.7f, _meleeAttack: 0.6f, _projectileAttack: 1.2f, _range: 2, _elasticDefense: 2.0f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5002", new Data(_id: "unit_5002", _name: "Chariot", _level: 4, _group: "CAVALRY", _culture: "egypt", _age: "bronze", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "melee", "charge", "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "ironSword", _rangedType: "bow", _armourType: "metal", _mountedType: "horse", _priotizedAttack: 1.8f, _meleeAttack: 0.8f, _projectileAttack: 1.0f, _range: 2, _elasticDefense: 0.6f, _armourDefense: 1.0f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5003", new Data(_id: "unit_5003", _name: "War Elephant", _level: 4, _group: "CAVALRY", _culture: "india", _age: "bronze", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "ironSword", _mountedType: "elephant", _priotizedAttack: 2.0f, _meleeAttack: 1.2f, _elasticDefense: 0.6f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5004", new Data(_id: "unit_5004", _name: "Hunnic Cavalry", _level: 2, _group: "CAVALRY", _culture: "step", _age: "iron", _basicEquipment: 1.0f, _basicTraining: 1.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "ironSpear", _armourType: "metal", _mountedType: "horse", _priotizedAttack: 1.2f, _meleeAttack: 0.8f, _elasticDefense: 1.0f, _armourDefense: 1.0f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5005", new Data(_id: "unit_5005", _name: "Frankish Knight", _level: 3, _group: "CAVALRY", _culture: "europe", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee", "charge" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "ironSpear", _armourType: "metal", _mountedType: "horse", _priotizedAttack: 1.4f, _meleeAttack: 0.8f, _elasticDefense: 0.8f, _armourDefense: 1.2f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5006", new Data(_id: "unit_5006", _name: "Cataphract", _level: 5, _group: "CAVALRY", _culture: "byzantin", _age: "iron", _basicEquipment: 4.0f, _basicTraining: 4.0f, _attackType: new List<string>(){ "melee", "charge", "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "ironSpear", _rangedType: "bow", _armourType: "metal", _mountedType: "horse", _priotizedAttack: 1.6f, _meleeAttack: 0.8f, _range: 2, _elasticDefense: 1.4f, _armourDefense: 1.6f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5007", new Data(_id: "unit_5007", _name: "Camel Rider", _level: 3, _group: "CAVALRY", _culture: "arab", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee", "charge", "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "ironSword", _rangedType: "bow", _armourType: "NaN", _mountedType: "camel", _priotizedAttack: 1.2f, _meleeAttack: 0.8f, _projectileAttack: 1.2f, _range: 2, _elasticDefense: 1.7f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5008", new Data(_id: "unit_5008", _name: "Could Iron Cavalry", _level: 3, _group: "CAVALRY", _culture: "china", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 3.0f, _armourDefense: 1.6f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5009", new Data(_id: "unit_5009", _name: "Black Rider", _level: 4, _group: "CAVALRY", _culture: "europe", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 3.0f, _armourDefense: 1.8f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5010", new Data(_id: "unit_5010", _name: "Mongol Kheshig", _level: 5, _group: "CAVALRY", _culture: "step", _age: "fire", _basicEquipment: 4.0f, _basicTraining: 4.0f, _armourDefense: 1.8f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5011", new Data(_id: "unit_5011", _name: "Cuirassier", _level: 5, _group: "CAVALRY", _culture: "europe", _age: "iron", _basicEquipment: 4.0f, _basicTraining: 3.0f, _armourDefense: 2.0f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5012", new Data(_id: "unit_5012", _name: "Armored Elephant", _level: 6, _group: "CAVALRY", _culture: "india", _age: "fire", _basicEquipment: 5.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "melee", "charge", "projectile", "siege" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "ironSword", _rangedType: "canon", _armourType: "NaN", _mountedType: "elephant", _priotizedAttack: 3.0f, _meleeAttack: 2.0f, _projectileAttack: 1.2f, _armorPiercingAttack: 1.5f, _siegeAttack: 2.0f, _range: 3, _elasticDefense: 0.8f, _armourDefense: 2.0f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_5013", new Data(_id: "unit_5013", _name: "Cossack Cavalry", _level: 4, _group: "CAVALRY", _culture: "europe", _age: "fire", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee", "charge", "projectile" }, _defenseType: new List<string>(){ "elastic" }, _meleeType: "ironSword", _rangedType: "firearm", _armourType: "NaN", _mountedType: "horse", _priotizedAttack: 1.2f, _meleeAttack: 1.6f, _projectileAttack: 2.0f, _range: 2, _elasticDefense: 1.7f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_6001", new Data(_id: "unit_6001", _name: "Trebuchet", _level: 3, _group: "SIEGE", _culture: "china", _age: "iron", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "siege" }, _rangedType: "crossbow", _armourType: "wood", _mountedType: "NaN", _siegeAttack: 2.8f, _range: 4, _elasticDefense: 0.0f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_6002", new Data(_id: "unit_6002", _name: "Ballista", _level: 3, _group: "SIEGE", _culture: "rome", _age: "iron", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "projectile", "siege" }, _defenseType: new List<string>(){ "elastic" }, _rangedType: "crossbow", _armourType: "wood", _mountedType: "NaN", _projectileAttack: 1.5f, _armorPiercingAttack: 1.5f, _siegeAttack: 1.8f, _range: 4, _elasticDefense: 0.5f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_6003", new Data(_id: "unit_6003", _name: "Mortar", _level: 5, _group: "SIEGE", _culture: "europe", _age: "fire", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "projectile", "siege" }, _defenseType: new List<string>(){ "elastic" }, _rangedType: "canon", _armourType: "metal", _mountedType: "NaN", _projectileAttack: 2.0f, _armorPiercingAttack: 2.0f, _siegeAttack: 3.0f, _range: 4, _elasticDefense: 0.5f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_6004", new Data(_id: "unit_6004", _name: "Singijeon", _level: 3, _group: "SIEGE", _culture: "korea", _age: "fire", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "projectile", "siege" }, _defenseType: new List<string>(){ "elastic" }, _rangedType: "bow", _armourType: "wood", _mountedType: "NaN", _projectileAttack: 3.0f, _range: 2, _elasticDefense: 0.5f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_6005", new Data(_id: "unit_6005", _name: "Giant Cannon", _level: 7, _group: "SIEGE", _culture: "Ottoman", _age: "fire", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "siege" }, _rangedType: "canon", _armourType: "metal", _mountedType: "NaN", _siegeAttack: 5.0f, _range: 4, _elasticDefense: 0.0f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_6006", new Data(_id: "unit_6006", _name: "Grenadier", _level: 2, _group: "SIEGE", _culture: "europe", _age: "fire", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "projectile", "siege" }, _defenseType: new List<string>(){ "elastic" }, _rangedType: "canon", _armourType: "NaN", _mountedType: "NaN", _siegeAttack: 2.0f, _range: 1, _elasticDefense: 1.0f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_6007", new Data(_id: "unit_6007", _name: "Howitzer", _level: 7, _group: "SIEGE", _culture: "korea", _age: "fire", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "projectile", "siege" }, _defenseType: new List<string>(){ "elastic" }, _rangedType: "canon", _armourType: "metal", _projectileAttack: 3.0f, _armorPiercingAttack: 3.0f, _siegeAttack: 4.0f, _range: 4, _elasticDefense: 0.5f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_6008", new Data(_id: "unit_6008", _name: "Rear-loading Cannon", _level: 9, _group: "SIEGE", _culture: "europe", _age: "fire", _basicEquipment: 3.0f, _basicTraining: 3.0f, _attackType: new List<string>(){ "projectile", "siege" }, _defenseType: new List<string>(){ "elastic" }, _rangedType: "canon", _armourType: "metal", _projectileAttack: 4.0f, _armorPiercingAttack: 4.0f, _siegeAttack: 6.0f, _range: 5, _elasticDefense: 0.5f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_7001", new Data(_id: "unit_7001", _name: "Sapper", _level: 2, _group: "SPECIAL", _culture: "china", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 1.0f, _defenseType: new List<string>(){ "elastic", "armour" }, _meleeType: "NaN", _rangedType: "canon", _siegeAttack: 2.0f, _range: 1, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_7002", new Data(_id: "unit_7002", _name: "Legionary Engineer", _level: 3, _group: "SPECIAL", _culture: "rome", _age: "iron", _basicEquipment: 2.0f, _basicTraining: 2.0f, _attackType: new List<string>(){ "melee" }, _defenseType: new List<string>(){ "formation", "armour" }, _meleeType: "ironSword", _armourType: "metal", _priotizedAttack: 1.4f, _meleeAttack: 1.4f, _formationDefense: 1.4f, _armourDefense: 1.4f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
		{"unit_7003", new Data(_id: "unit_7003", _name: "Laborer", _level: 1, _group: "SPECIAL", _culture: "china", _age: "iron", _basicEquipment: 1.0f, _basicTraining: 1.0f, _meleeType: "NaN", _formationDefense: 0.6f, _faceimage: "unit_0001", _faceCenter: new List<float>(){ 0.6f, 0.8f })},
	};
}
